<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FGTOVGJ" failures="0" tests="6" name="com.harshi.Testng.AttributeTest" time="0.241" errors="1" timestamp="2023-12-17T20:40:56 IST" skipped="2">
  <testcase classname="com.harshi.Testng.AttributeTest" name="testTwo" time="0.002"/>
  <testcase classname="com.harshi.Testng.AttributeTest" name="r3" time="0.000">
    <skipped/>
  </testcase> <!-- r3 -->
  <testcase classname="com.harshi.Testng.AttributeTest" name="r1" time="0.013"/>
  <testcase classname="com.harshi.Testng.AttributeTest" name="r2" time="0.224">
    <error message="Method com.harshi.Testng.AttributeTest.r2() didn&#039;t finish within the time-out 200" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.harshi.Testng.AttributeTest.r2() didn't finish within the time-out 200
at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
at app//com.harshi.Testng.AttributeTest.r2(AttributeTest.java:41)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- r2 -->
  <testcase classname="com.harshi.Testng.AttributeTest" name="testOne" time="0.002"/>
  <testcase classname="com.harshi.Testng.AttributeTest" name="testThree">
    <skipped/>
  </testcase> <!-- testThree -->
</testsuite> <!-- com.harshi.Testng.AttributeTest -->
